version: "3"

# name: nginx-endpoint
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-endpoint
    restart: always
    networks:
      - nextjs-docker_frontend
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
